### ISSUE TITLE
Converter Hanging

### ISSUE THREAD

**Issue by pamar1908** [Sicos1977/ChromiumHtmlToPdf#106]
Hi, I am trying to run the following but it hangs at the converting line. I have tried without specifying the executable path as well. Thanks for any help.

`Using conv As New Converter("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
            Dim ps As New Settings.PageSettings(Enums.PaperFormat.A4)
            conv.ConvertToPdf(html_text, "C:\Users\User\Downloads\mypdf.pdf", ps)
End Using`

**Comment by pamar1908** [comment]
How can I do this?

**Comment by Sicos1977** [comment]
You probably set it to false from the Constructor

```c#
        /// <summary>
        ///     Creates this object and sets it's needed properties
        /// </summary>
        /// <param name="chromeExeFileName">When set then this has to be the full path to the chrome executable.
        ///     When not set then then the converter tries to find Chrome.exe by first looking in the path
        ///     where this library exists. After that it tries to find it by looking into the registry</param>
        /// <param name="userProfile">
        ///     If set then this directory will be used to store a user profile.
        ///     Leave blank or set to <c>null</c> if you want to use the default Chrome user profile location
        /// </param>
        /// <param name="logger">When set then logging is written to this ILogger instance for all conversions at the Information log level</param>
        /// <param name="useCache">When <c>true</c> (default) then Chrome uses it disk cache when possible</param>
        /// <exception cref="FileNotFoundException">Raised when <see cref="chromeExeFileName" /> does not exists</exception>
        /// <exception cref="DirectoryNotFoundException">
        ///     Raised when the <paramref name="userProfile" /> directory is given but does not exists
        /// </exception>
        public Converter(string chromeExeFileName = null,
                         string userProfile = null,
                         ILogger logger = null,
                         bool useCache = true)
        {
```

**Comment by Sicos1977** [comment]
Or you called the methode

```c#
        #region ResetChromeArguments
        /// <summary>
        ///     Resets the <see cref="DefaultChromeArguments" /> to their default settings
        /// </summary>
        public void ResetChromeArguments()
        {
            WriteToLog("Resetting Chrome arguments to default");

            _defaultChromeArgument = new List<string>();
            AddChromeArgument("--headless");
            AddChromeArgument("--disable-gpu");
            AddChromeArgument("--hide-scrollbars");
            AddChromeArgument("--mute-audio");
            AddChromeArgument("--disable-background-networking");
            AddChromeArgument("--disable-background-timer-throttling");
            AddChromeArgument("--disable-default-apps");
            AddChromeArgument("--disable-extensions");
            AddChromeArgument("--disable-hang-monitor");
            AddChromeArgument("--disable-prompt-on-repost");
            AddChromeArgument("--disable-sync");
            AddChromeArgument("--disable-translate");
            AddChromeArgument("--metrics-recording-only");
            AddChromeArgument("--no-first-run");
            AddChromeArgument("--disable-crash-reporter");
            AddChromeArgument("--remote-debugging-port", "0");

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                WriteToLog("Detected Linux operating system, adding the parameter '--no-sandbox'");
                AddChromeArgument("--no-sandbox");
            }

            SetWindowSize(WindowSize.HD_1366_768);
            _useCache = false;
        }
        #endregion
```

**Comment by Sicos1977** [comment]
I just released a new nuget package, please check if that fixes your issue

**Comment by pamar1908** [comment]
The new package cannot be installed due to the following:

Unable to find a version of 'AngleSharp' that is compatible with 'AngleSharp.Css 0.17.0 constraint: AngleSharp (>= 0.17.0 && < 0.18.0)', 'HtmlSanitizer 8.0.645 constraint: AngleSharp (= 0.17.1)'.

**Comment by Sicos1977** [comment]
Weird, I did not get any errors when building the package... have to look into that.

**Comment by Sicos1977** [comment]
Should be fixed in 2.6.9 ... there was a dependency problem between the AngleSharp packages

**Comment by Sicos1977** [comment]
And?

**Comment by pamar1908** [comment]
Sorry we had some IT disaster today. Thank you very much for the releases. Unfortunately, it is still hanging at Enabling/Disabling Cashing (depending on setting).

**Comment by Sicos1977** [comment]
Can you try and use normale Chrome (not the portabble version) and see if that makes any difference.

**Comment by Sicos1977** [comment]
Ow... are u using Chrome from a windows service and is that service user running onder local system?

**Comment by pamar1908** [comment]
Yes I am trying it locally on my PC.

**Comment by pamar1908** [comment]
I am not running it as a Windows Service. I am running a Windows Forms app. I have also tried on another PC without any luck.

**Comment by pamar1908** [comment]
Did you find any reason why I might be getting the cashing error?  Any way to bypass this? I have tried portable Chrome and it does the same
